/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import DaoImp.PacientesDaoImp;
import POJO.Pacientes;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.List;
import Util.RandomConnection;
import Main.ListaPacientes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.text.WordUtils;

/**
 *
 * @author Reymundo Tenorio
 */

public class BuscarPaciente extends javax.swing.JDialog {
Pacientes e = null;

   javax.swing.JTable tabla = new JTable();

    DefaultTableModel model = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int row, int column) {
       //all cells false
       return false;
    }
};
    public JTable getTabla() {
        return tabla;
    }

    public void setTabla(JTable tabla) {
        this.tabla = tabla;
    }
    /**
     * Creates new form BuscarPaciente
     */
    public BuscarPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
       
        initComponents();
         btnbuscar.setToolTipText("Buscar Paciente");
        btncancel.setToolTipText("Cancelar");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnbuscar = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(5, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número de Cédula");
        jLabel1.setEnabled(false);
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setEnabled(false);
        jPanel1.add(jFormattedTextField1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombres Del Paciente");
        jLabel3.setEnabled(false);
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3);

        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnbuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar);

        btncancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncancel.setText("Cancelar");
        jPanel2.add(btncancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Buscar Por:");
        jPanel3.add(jLabel2);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Número Cedula", "Nombres" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel3.add(jComboBox1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(411, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
int index  = jComboBox1.getSelectedIndex();


 try {
            new RandomConnection(("Pacientes.dat")).Conectar();
        } catch (FileNotFoundException ex) {
            System.out.println("Archivo No Encontrado");
        } catch (IOException ex) {
            System.out.println("Error al Conectar");
        }
        
        
    
            PacientesDaoImp cdi = new PacientesDaoImp();
            
            
        try {
            List<Pacientes> cursos = cdi.EncontrarTodos();
        } catch (IOException ex) {
            System.out.println("Error al Leer Todos");
        }
        
           List<Pacientes> cursos = null;
        try {
            cursos = cdi.EncontrarTodos();
        } catch (IOException ex) {
            System.out.println("No Se Pudo Leer Todos");
        }
    try {        
        
        if(cdi.Raf()==0){
                System.out.println("No hay registros");
            }
    } catch (IOException ex) {
        Logger.getLogger(BuscarPaciente.class.getName()).log(Level.SEVERE, null, ex);
    }

switch(index){
    
    case 0: 
//        try {
//            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
//        } catch (java.text.ParseException ex) {
//            ex.printStackTrace();
//        }
//    jLabel1.setText("Número de Cédula del Paciente");
    
        
//        try {
//            new RandomConnection(("Pacientes.dat")).Conectar();
//        } catch (FileNotFoundException ex) {
//            System.out.println("Archivo No Encontrado");
//        } catch (IOException ex) {
//            System.out.println("Error al Conectar");
//        }
        
//        
//    
//            PacientesDaoImp cdi = new PacientesDaoImp();
//            
//            
//        try {
//            List<CursosINATEC> cursos = cdi.EncontrarTodos();
//        } catch (IOException ex) {
//            System.out.println("Error al Leer Todos");
//        }
//        
//           List<CursosINATEC> cursos = null;
//        try {
//            cursos = cdi.EncontrarTodos();
//        } catch (IOException ex) {
//            System.out.println("No Se Pudo Leer Todos");
//        }
        
        try {
//            if(cdi.Raf()==0){
//                System.out.println("No hay registros");
//            }
//            
//            else{
             
                String cedula= jFormattedTextField1.getText();
                
                
       
                int x=0;
                
                try{
                e = cdi.BuscarPorCedula(cedula);
           
                }catch(java.io.EOFException n){
                    System.out.println("No Encontrado, raf :"+cdi.Raf());
                    x=1;
                }
                
                if(x!=1){
                if(e.getNombres()==null){
                    System.out.println("no encontrado");
                    
                }
                
              
        
                else{
                    
                    
                    String header [] = {"Paciente No","Cedula","Nombres","Apellidos","Edad","Ocupacion","Direccion","Telefono","Expediente"};
              
              model.setColumnIdentifiers(header);
              
              String Datos[] = new String[9];
              model.setNumRows(0);
              
              
              
             //  for ( Pacientes e : cursos  ){
              
              Datos [0]=String.valueOf(e.getId());
              Datos [1]=e.getCedula();
              Datos [2]=e.getNombres();
              Datos [3]=e.getApellidos();
              Datos [4]=String.valueOf(e.getEdad());
              Datos [5]=e.getOcupacion();
              Datos [6]=e.getDireccion();
                      Datos [7]=e.getTelefonos();
                      Datos [8]=e.getExpediente();
                    
              
              model.addRow(Datos);
              tabla.setModel(model);
               
               // }       
                
//                    System.out.println("\nID: " + e.getId());
//                                System.out.println("\nNombre: " + e.getNombre());
//                                System.out.println("\nAcuerdo: "+e.getAcuerdo());
//                                System.out.println("\nCodigo: "+e.getCodigo());
//                                System.out.println("\nFecha: " + e.getFecha());
//                                System.out.println("\nActivo "+e.isActivo());
                }
                }
//            }
       this.dispose();
        } catch (IOException ex) {
            System.out.println("Aqui!");
        }
        
        break;
        
    case 1:  
//            jFormattedTextField1 = new javax.swing.JFormattedTextField();
//        jLabel1.setText("Nombres Del Paciente");
        
       
        
        try {
            
            
            //else{
             
                String Nombre= jTextField1.getText().trim();
                
                
       
                int x=0;
                
                try{
                e = cdi.BuscarPorNombres(Nombre);
           
                }catch(java.io.EOFException n){
                    System.out.println("No Encontrado, raf :"+cdi.Raf());
                    x=1;
                }
                
                if(x!=1){
                if(e.getNombres()==null){
                    System.out.println("no encontrado");
                    
                }
                
              
        
                else{
                    
                    
                    String header [] = {"Paciente No","Cedula","Nombres","Apellidos","Edad","Ocupacion","Direccion","Telefono","Expediente"};
              
              model.setColumnIdentifiers(header);
              
              String Datos[] = new String[9];
              model.setNumRows(0);
              
              
              
             //  for ( Pacientes e : cursos  ){
              
              Datos [0]=String.valueOf(e.getId());
              Datos [1]=e.getCedula();
              Datos [2]=e.getNombres();
              Datos [3]=e.getApellidos();
              Datos [4]=String.valueOf(e.getEdad());
              Datos [5]=e.getOcupacion();
              Datos [6]=e.getDireccion();
                      Datos [7]=e.getTelefonos();
                      Datos [8]=e.getExpediente();
                    
              
              model.addRow(Datos);
              tabla.setModel(model);
               
               // }       
                
//                    System.out.println("\nID: " + e.getId());
//                                System.out.println("\nNombre: " + e.getNombre());
//                                System.out.println("\nAcuerdo: "+e.getAcuerdo());
//                                System.out.println("\nCodigo: "+e.getCodigo());
//                                System.out.println("\nFecha: " + e.getFecha());
//                                System.out.println("\nActivo "+e.isActivo());
                }
                }
            //}
       this.dispose();
        } catch (IOException ex) {
            System.out.println("Aqui!");
        }
        
        
        break;
        
    default: break;
    
    
    
}



//ListaPacientes pn = new ListaPacientes();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       int index  = jComboBox1.getSelectedIndex();

switch(index){
    
    case 0:  try {
        jFormattedTextField1.setVisible(true);
        jFormattedTextField1.setEnabled(true);
        
            jTextField1.setVisible(false);
        jTextField1.setEnabled(false);
        
        jLabel1.setVisible(true);
        jLabel1.setEnabled(true);
        
             jLabel3.setVisible(false);
        jLabel3.setEnabled(false);
        
        
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
    jLabel1.setText("Número de Cédula del Paciente");
    
        
        break;
        
    case 1:  
            //jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
      jFormattedTextField1.setVisible(false);
        jFormattedTextField1.setEnabled(false);
        
        jTextField1.setVisible(true);
        jTextField1.setEnabled(true);
        
        jLabel3.setVisible(true);
        jLabel3.setEnabled(true);
        
        jLabel1.setVisible(false);
        jLabel1.setEnabled(false);
     //   jLabel1.setText("Nombres Del Paciente");
        break;
        
        default: break;
}// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jLabel1.setVisible(true);
jLabel1.setEnabled(true);
jLabel3.setVisible(false);
jFormattedTextField1.setVisible(true);
jFormattedTextField1.setEnabled(true);
jTextField1.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
 jTextField1.setText(WordUtils.capitalizeFully(jTextField1.getText()));  
 
 
 // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyTyped

    public Pacientes getE() {
        return e;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscarPaciente dialog = new BuscarPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
