package Main;

import Funciones.PintarEscritorio;
import Funciones.Reloj;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Reymundo Tenorio
 */
public class Exa extends javax.swing.JFrame {

    /**
     * Creates new form Exa
     */
    public Exa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Socrátes Flores - Contro de Pacientes");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        //jDesktopPane1 = new DesktopConFondo();
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setDoubleBuffered(true);
        jPanel1.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lbHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(lbHora);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Gestiones");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo Paciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Ver Lista de Pacientes");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Nuevo Expediente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Ver Expedientes de Pacientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//
//    public JDesktopPane getjDesktopPane1() {
//        return jDesktopPane1;
//    }
//
//    public void setjDesktopPane1(JDesktopPane jDesktopPane1) {
//        this.jDesktopPane1 = jDesktopPane1;
//    }

    
    
    File fondo=new File("Imagenes//hdfondo.jpg");
    
    private void setCentrarJInternalFrame(JInternalFrame jifrm)
    {
        jifrm.setLocation(jifrm.getParent().getWidth()/2 - jifrm.getWidth()/2 ,jifrm.getParent().getHeight()/2 - jifrm.getHeight()/2 - 20);
    }

    
    
    

    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
 NuevoPaciente r = new NuevoPaciente();
this.jDesktopPane1.add(r);
r.setVisible(true); 

setCentrarJInternalFrame(r);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

   

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     ListaPacientes c = new ListaPacientes();
     this.jDesktopPane1.add(c);
     c.setVisible(true);
        
     
     setCentrarJInternalFrame(c);
        
            
     
     
            
            
     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
NuevoExpediente osi = new NuevoExpediente();
this.jDesktopPane1.add(osi);
osi.setVisible(true);

setCentrarJInternalFrame(osi);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
VerExpedientes te = new VerExpedientes();
this.jDesktopPane1.add(te);
te.setVisible(true);

setCentrarJInternalFrame(te);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

//    Thread h1;
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
     //  Openning O = new Openning();
//     Openning.FillProgressBarThread fpt = new Openning.FillProgressBarThread();
//            fpt.setFlag(true);
//            Thread t = new Thread(fpt);
//            t.start();
        
//        java.util.Date fecha = new Date();
//System.out.println (fecha);
         Reloj watch = new Reloj();
      // h1 = new Thread(watch.getH1());
       
        watch.setLblHora(lbHora);
     // h1.start();
        
        watch.Iniciar();
        
        //watch.run();
        
        lbHora = watch.getLblHora();
     
        cargarImagen(jDesktopPane1,fondo);
        
        //  ((DesktopConFondo) jDesktopPane1).setImagen("Imagenes/imagen.jpg");  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
     //watch.setFlag(false);   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    
    
    public  void cargarImagen(JDesktopPane jDeskp,File fileImagen) {
        try{
            BufferedImage image = ImageIO.read(fileImagen);
             jDeskp.setBorder(new PintarEscritorio(image)); 
        }
        catch (Exception e){   System.out.println("No cargo imagen, sorry");   }
    
	 

} 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        try{
//        javax.swing.UIManager.setLookAndFeel(new SyntheticaSimple2DLookAndFeel());
//        }catch(ParseException | UnsupportedLookAndFeelException ex){
//            System.out.println("Ecsd");
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Exa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables
}
