/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Reymundo Tenorio
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Openning
     */
//    public Splash() {
//        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jProgressBar1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/Splash.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(532, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private Timer timer;
    int cont;
    private String newline;
    public final static int ONE_SECOND = 10;

    public Splash()
    {
        
        initComponents();
//       setUndecorated(true);
//     setOpacity(0.5f);
        
//        LookAndFeelInfo[] lista = UIManager.getInstalledLookAndFeels();
//
//for (int i = 0; i < lista.length; i++) {
//
//    System.out.println(lista[i].getClassName());
//
//}
       cont =-1;
        initComponents();
        jProgressBar1.setValue(0);
        jProgressBar1.setStringPainted(true);
        timer = new Timer(ONE_SECOND, new TimerListener());

         timer.start();
    }

    class TimerListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent evt) {
            cont++;
           // jLabel1.setText("nume es :"+cont);
            jProgressBar1.setValue(cont);
            if(cont==120)
            {
                  timer.stop();
                  esconder();

                JFrame exa = new Exa();
                exa.setVisible(true);
//                Identificacion.show();

            }
        }
    }
    
        public void esconder()
    {
        this.setVisible(false);
    }
        
   public void activar()
    {
        timer.start();
    }

//
//    public class FillProgressBarThread implements Runnable {
//        private int i;
//        private boolean flag;
//
//        public void setFlag(boolean flag) {
//            this.flag = flag;
//        }
//
//        public void setI(int i) {
//            this.i = i;
//        }
//
//        @Override
//        @SuppressWarnings("empty-statement")
//        public void run() {
//            if (i > 100) {
//                i = 1;
//            }
//            while (flag) {
//                
//                
//
//                jProgressBar1.setValue(i++);
//                try {
//                    Thread.sleep(50);
//                } catch (InterruptedException ex) {
//                }
//                if(i > 100){
//                    flag = false;
// examen.Exa x = new Exa();
// x.setVisible(true);
// x.toFront();
//
// 
// 
//                }
//            }
//            
//        }
//    }

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//FillProgressBarThread fpt = new FillProgressBarThread();
//            fpt.setFlag(true);
//            Thread t = new Thread(fpt);
//            t.start();
    //   new PantallaCargandoMain();
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
//            try {
//                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                    if ("Nimbus".equals(info.getName())) {
//                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                        break;
//                    }
//                }
//            } catch (ClassNotFoundException ex) {
//                java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (InstantiationException ex) {
//                java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (IllegalAccessException ex) {
//                java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//                java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//            }
//            
            
            
            
            try 
    {
      //<<<<<<<<<<----------------synthetica
      
//      SyntheticaLookAndFeel.setWindowsDecorated(false);
//      SyntheticaLookAndFeel.setUseSystemFileIcons(true);
     
      //UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
     
     //activando THEMAS 
     //+
     //+
     //UIManager.setLookAndFeel(new SyntheticaBlackMoonLookAndFeel());
//     UIManager.setLookAndFeel(new SyntheticaBlackStarLookAndFeel());
     //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaSilverMoonLookAndFeel");
     
     //de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel.setWindowsDecorated(false);
     //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaGreenDreamLookAndFeel");
     
     //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueSteelLookAndFeel");
     //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueMoonLookAndFeel");
     //UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlueIceLookAndFeel");
     //+
     //+	
     //activando THEMAS  
      

      //------------------------->>>>synthetica
      
      
      //---------------------->>>>>>>>liquid
      
        /*UIManager.setLookAndFeel(new LiquidLookAndFeel());
        com.birosoft.liquid.LiquidLookAndFeel.setStipples(false);
        com.birosoft.liquid.LiquidLookAndFeel.setDefaultRowBackgroundMode(true);
        com.birosoft.liquid.LiquidLookAndFeel.setPanelTransparency(true);
        com.birosoft.liquid.LiquidLookAndFeel.setLiquidDecorations(true);*/
        
      //<<<<<<<<<<<<<<<<<<<<<<<-----------------iquid
      //---------------------->>>>>>>>NimROD
UIManager.setLookAndFeel( new com.nilo.plaf.nimrod.NimRODLookAndFeel());
	 //<<<<<<<<<<<<<<<<<<<<<<<-----------------NimROD	  

        
                 
        
    } catch (Exception e) 
    {
          System.out.println("NO SE PUEDE CARGAR");
          
    }

            
//            
//            try{
//            
//            UIManager.setLookAndFeel(new SyntheticaWhiteVisionLookAndFeel());
//            //</editor-fold>
//        } catch (ParseException ex) {
//            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
//        }   catch (UnsupportedLookAndFeelException ex) {
//                Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
//            }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
//                Splash f = new Splash();
//        PaintJPanel p = new PaintJPanel("/Imagenes/intro.jpg");
//        f.add(p);
//        f.setVisible(true);
                
               new Splash().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
