/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Funciones.Secuencial;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Reymundo Tenorio
 */
public class VerExpedientes extends javax.swing.JInternalFrame {
    private DefaultTreeModel model;
    private DefaultMutableTreeNode root;
    private File f, files[];

    /**
     * Creates new form VerExpedientes
     */
    public VerExpedientes() {
        initComponents();
        btnclose.setToolTipText("Cerrar Pestaña Seleccionada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnclose = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ver Expedientes");
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jSplitPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSplitPane1.setDividerLocation(210);
        jSplitPane1.setDividerSize(10);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setOneTouchExpandable(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        root = new DefaultMutableTreeNode("Expedientes");
        model = new DefaultTreeModel(root);
        jTree1 = new javax.swing.JTree(model);
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setFocusTraversalPolicyProvider(true);
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnclose.setText("X");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel3.add(btnclose);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 716, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
  f = new File("Expedientes");
        if (!f.exists()) {
            System.out.println("No exist");
        return;
        }
        files = f.listFiles();
        for (File ff : files) {
            int n = root.getChildCount();
            model.insertNodeInto(
                    new DefaultMutableTreeNode(ff.getName())
                    , root, n);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
 if(evt.getClickCount() == 2 
                && evt.getButton() == MouseEvent.BUTTON1){
            TreePath path = jTree1.getSelectionPath();
            if(path == null){
                return;
            }
            DefaultMutableTreeNode node = 
                    (DefaultMutableTreeNode) 
                    path.getLastPathComponent();
            if(node.isRoot()){
                return;
            }
            File file = new File("Expedientes/"
                    +node.toString());
            
            System.out.println("File "+file);
            try {
                String texto = Secuencial.readFile(file);
                System.out.println(texto);
                TextPanel tp = new TextPanel();
                tp.getjTextArea().setText(texto);
                jTabbedPane1.addTab(file.getName(), tp);
            } catch (IOException ex) {
                
            }
        }
 // TODO add your handling code here:
    }//GEN-LAST:event_jTree1MouseClicked

    
    public void AbrirExpendiente(String rut){
        try {
            File file = new File("Expedientes/"
                        +rut+".txt");
                
                System.out.println("File "+file);
                
                    String texto = Secuencial.readFile(file);
                  //  System.out.println(texto);
                    TextPanel tp = new TextPanel();
                    tp.getjTextArea().setText(texto);
                    jTabbedPane1.addTab(file.getName(), tp);
        } catch (IOException ex) {
            System.out.println("No Se Puedo Abrir el Expediente");
        }
          
        
        
    }
    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
 Component c = jTabbedPane1.getSelectedComponent();
        if(c == null){
            return;
        }
       jTabbedPane1.remove(c);        // TODO add your handling code here:
    }//GEN-LAST:event_btncloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
